CREATE TABLE IF NOT EXISTS application_tracking_counters (
  division TEXT NOT NULL,
  year TEXT NOT NULL,
  month TEXT NOT NULL,
  serial INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (division, year, month)
);

CREATE TABLE IF NOT EXISTS application_item_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  officer_role TEXT NOT NULL,
  item_name TEXT NOT NULL,
  provider_email TEXT NOT NULL,
  provider_name TEXT,
  provider_designation TEXT,
  provider_role TEXT,
  desk_officer_name TEXT,
  desk_signature TEXT,
  desk_signed_at TEXT,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'Forwarded for Approval',
  officer_service_info TEXT,
  provider_signature TEXT,
  provider_signed_at TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (application_id, officer_role, item_name)
);

CREATE INDEX IF NOT EXISTS idx_assignment_provider_email ON application_item_assignments(provider_email);
CREATE INDEX IF NOT EXISTS idx_assignment_application_id ON application_item_assignments(application_id);
CREATE INDEX IF NOT EXISTS idx_assignment_officer_role ON application_item_assignments(officer_role);
CREATE INDEX IF NOT EXISTS idx_assignment_status ON application_item_assignments(status);
CREATE INDEX IF NOT EXISTS idx_assignment_updated_at ON application_item_assignments(updated_at);
