CREATE TABLE IF NOT EXISTS data_share_access_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER REFERENCES data_share_clients(id) ON DELETE SET NULL,
  client_name TEXT,
  direction TEXT NOT NULL DEFAULT 'Pull',
  scope TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  method TEXT NOT NULL,
  status_code INTEGER NOT NULL,
  row_count INTEGER NOT NULL DEFAULT 0,
  ip TEXT,
  user_agent TEXT,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_data_share_access_logs_client_id ON data_share_access_logs(client_id);
CREATE INDEX IF NOT EXISTS idx_data_share_access_logs_created_at ON data_share_access_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_data_share_access_logs_direction ON data_share_access_logs(direction);
