CREATE TABLE IF NOT EXISTS data_share_clients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  token_hash TEXT UNIQUE NOT NULL,
  scopes TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_data_share_clients_token_hash ON data_share_clients(token_hash);
CREATE INDEX IF NOT EXISTS idx_data_share_clients_status ON data_share_clients(status);
