CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  password_hash TEXT,
  name_bn TEXT NOT NULL,
  role TEXT NOT NULL,
  division TEXT,
  status TEXT DEFAULT 'Active',
  photo TEXT,
  signature TEXT,
  pending_signature TEXT,
  signature_pending_at TEXT,
  must_change_password BOOLEAN DEFAULT false,
  designation TEXT,
  mobile TEXT,
  extra_permissions TEXT,
  denied_permissions TEXT
);

CREATE TABLE IF NOT EXISTS divisions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  head TEXT NOT NULL,
  employees INTEGER DEFAULT 0,
  status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  name_bn TEXT NOT NULL,
  description TEXT,
  permissions TEXT,
  status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_no TEXT UNIQUE NOT NULL,
  user_email TEXT NOT NULL,
  user_name TEXT NOT NULL,
  division TEXT NOT NULL,
  service_type TEXT NOT NULL,
  problem_details TEXT,
  category_problem_details TEXT,
  status TEXT DEFAULT 'Submitted',
  submission_date TEXT NOT NULL,
  applicant_signature TEXT,
  applicant_signed_at TEXT,
  div_head_signature TEXT,
  div_head_signed_at TEXT,
  div_head_email TEXT,
  designation TEXT,
  mobile TEXT,
  officer_signature TEXT,
  officer_signed_at TEXT,
  officer_name TEXT,
  hw_officer_sig TEXT,
  hw_officer_date TEXT,
  hw_officer_name TEXT,
  nw_officer_sig TEXT,
  nw_officer_date TEXT,
  nw_officer_name TEXT,
  sw_officer_sig TEXT,
  sw_officer_date TEXT,
  sw_officer_name TEXT,
  mnt_officer_sig TEXT,
  mnt_officer_date TEXT,
  mnt_officer_name TEXT,
  officer_designation TEXT,
  officer_service_info TEXT,
  officer_action_details TEXT
);

CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS telephone_directory_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  designation TEXT,
  division TEXT,
  intercom TEXT,
  mobile TEXT,
  ip_number TEXT,
  email TEXT,
  room_no TEXT,
  notes TEXT,
  status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_email TEXT,
  user_name TEXT,
  user_role TEXT,
  action TEXT NOT NULL,
  method TEXT NOT NULL,
  path TEXT NOT NULL,
  status_code INTEGER,
  details TEXT
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_applications_user_email ON applications(user_email);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_applications_division ON applications(division);
CREATE INDEX IF NOT EXISTS idx_applications_submission_date ON applications(submission_date);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_email ON audit_logs(user_email);
